# -*- coding: utf-8 -*-
"""
Created on Thu Sep 14 14:05:20 2017

@author: ysyong
Triangular, pentagonal, and hexagonal
Problem 45 
    Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    
    Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
    Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
    Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
    It can be verified that T285 = P165 = H143 = 40755.
    
    Find the next triangle number that is also pentagonal and hexagonal.
"""

import math
m = 286
while True:
    n = (1+sqrt(1+4*3*(m**2+m)))/(2*3)
    o = (2+sqrt(4+4*4*(m**2+m)))/(2*4)
    if n%1 == 0 and o%1 == 0:
        Tn = m*(m+1)/2
        Pn = n*(3*n-1)/2
        Hn = o*(2*o-1)
        if Tn == Pn and Pn == Hn:
            break
    m += 1


print("The next triangle number that is also pentagonal and hexagonal is",int(Tn))